sudo: false

language: c
os: linux

dist: trusty

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

env:
  - CHOOSENIM_CHOOSE_VERSION="devel"

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

before_script:
  - set -e

script:
  - nimble test

before_deploy:
  - find src/ -name '*.nim' -exec nim doc {} \;
  - mkdir doc
  - mv *.html nimdoc.out.css doc/

deploy:
  provider: pages
  local-dir: "doc/"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
